# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
    # Runs on pushes targeting the default branch
    push:
        branches: ['main']

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

    # Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

# Allow one concurrent deployment
concurrency:
    group: 'pages'
    cancel-in-progress: true

jobs:
    # Single deploy job since we're just deploying
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test
            - name: Build
              run: npm run build
            - name: Setup Pages
              uses: actions/configure-pages@v5
            - name: copy module public files
              run: |
                  # Copy 3D module public files
                  mkdir -p ./dist/3d-renderer && cp -r ./dist/js/modules/renderer/3d/public/index.html dist/3d-renderer/index.html
                  # Copy pathfinding module public files
                  mkdir -p ./dist/pathfinding/a-star && cp -r ./dist/js/modules/pathfinding/a-star/public/index.html dist/pathfinding/a-star/index.html
                  mkdir -p ./dist/pathfinding/minimum-spanning-tree && cp -r ./dist/js/modules/pathfinding/minimum-spanning-tree/public/index.html dist/pathfinding/minimum-spanning-tree/index.html
                  mkdir -p ./dist/pathfinding/animated-minimum-spanning-tree && cp -r ./dist/js/modules/pathfinding/minimum-spanning-tree/public/animated.html dist/pathfinding/animated-minimum-spanning-tree/index.html
                  mkdir -p ./dist/particle-life && cp -r ./dist/js/modules/particle/public/index.html dist/particle-life/index.html
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  # Upload dist folder
                  path: './dist'
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
